name: reddit-mental-health-sentiment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - pip:
    - python-dotenv
    - mkdocs
    - -e .